config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :gossips
  root 'gossips#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :gossips
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /gossips
  # GET /gossips.json
  def index
    @gossips = Gossip.all.order('created_at DESC')
    @gossip = Gossip.new
    @users = User.all
  end

  # GET /gossips/1
  # GET /gossips/1.json
  def show; end

  # GET /gossips/new
  def new
    @gossip = current_user.gossips.build
  end

  # GET /gossips/1/edit
  def edit; end

  # POST /gossips
  # POST /gossips.json
  def create
    @gossip = current_user.gossips.build(gossip_params)

    respond_to do |format|
      if @gossip.save
        format.html { redirect_to root_path, notice: 'Gossip was successfully created.' }
        format.json { render root_path, status: :created, location: @gossip }
      else
        format.html { render root_path }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gossips/1
  # PATCH/PUT /gossips/1.json
  def update
    respond_to do |format|
      if @gossip.update(gossip_params)
        format.html { redirect_to @gossip, notice: 'Gossip was successfully updated.' }
        format.json { render :show, status: :ok, location: @gossip }
      else
        format.html { render :edit }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gossips/1
  # DELETE /gossips/1.json
  def destroy
    @gossip.destroy
    respond_to do |format|
      format.html { redirect_to gossips_url, notice: 'Gossip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gossip
    @gossip = Gossip.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def gossip_params
    params.require(:gossip).permit(:body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/_feed.html.erb
<div class="column is-6">
  <div class="card add-gossip is-hidden-mobile">
    <% if user_signed_in? %>
      <div class="card-content">
          <div class="media">
            <div class="media-left">
                <p class="image is-48x48">
                  <%= gravatar_image_tag(current_user.email, size: 48, alt: current_user.name) %>
                </p>
            </div>
            <div class="media-content">
              <p class="title is-5">Hey, <%= current_user.name %>! Any juicy gossip to share?</p>
            </div>
          </div>

          <div class="content">

            <%= form_for @gossip do |form| %>
              <% if @gossip.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>

                  <ul>
                    <% gossip.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="field">
                <%= form.text_area :body, class: "textarea", value: "OMG! Turns out...", autofocus: true %>
              </div>

              <div class="actions">
                <%= form.submit class: "button is-fullwidth is-link is-outlined" %>
              </div>
            <% end %>
          </div>
      </div>
    <% else %>
      <div class="card-content">
          <h2 class="title is-3 is-spaced">Share some Gossip!<h2>
          <div class="columns is-1 is-variable">
              <div class="column">
                <%= link_to 'Sing-up', new_user_registration_path, class: "button is-medium is-fullwidth is-link is-outlined" %>
              </div>
              <div class="column">
                <%= link_to 'Log-in', new_user_session_path, class: "button is-medium is-fullwidth is-info is-outlined" %>
              </div>
          </div>
      </div>
    <% end %>
  </div>
  <% @gossips.each do |gossip| %>
    <div class="gossip-container">

      <div class="name-lockup">

        <%= gravatar_image_tag(gossip.user.email, alt: gossip.user.name, class: "avatar") %>
        <div class="name"><%= gossip.user.name %> <span>@<%= gossip.user.username%></span></div>

      </div>

      <blockquote>
        <%= gossip.body %>
      </blockquote>

      <div class="actions">
        <i class="icon-reply fa fa-reply-all"></i>
        <i class="icon-spread fa fa-bullhorn"> 0</i>
        <i class="icon-like fa fa-heart"> 1</i>
        <i class="icon-dislike fa fa-thumbs-o-down"> 0</i>
        <i class="icon-comment fa fa-comment-o"> 0</i>
        <i class="icon-quote-gossiper fa fa-quote-right"> 0</i>
        <% if user_signed_in? && current_user.id == gossip.user.id %>
          <%= link_to gossip, class: "icon-show" do %>
            <i class="fa fa-link"></i>
          <% end %>
          <%= link_to edit_gossip_path(gossip), class: "icon-edit" do %>
            <i class="fa fa-pencil-square-o"></i>
          <% end %>
          <%= link_to gossip, method: :delete, data: { confirm: 'Are you sure you want to delete this Gossip?' }, class: "icon-delete" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        <% end %>
      </div>

      <span class="time"><%= time_ago_in_words(gossip.created_at) %> ago</span>

    </div>
  <% end %>
</div>

app/views/gossips/_form.html.erb
<%= form_with(model: gossip, local: true) do |form| %>
  <% if gossip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>

      <ul>
        <% gossip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :body, class: "textarea"%>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-fullwidth is-info is-outlined" %>
  </div>
<% end %>

app/views/gossips/_trends.html.erb
<div class="column">

  <div class="card add-gossip is-hidden-desktop">
    <% if user_signed_in? %>
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <p class="image is-48x48">
                  <%= gravatar_image_tag(current_user.email, size: 48, alt: current_user.name) %>
                </p>
              </div>
              <div class="media-content">
                <p class="title is-5">Hey, <%= current_user.name %>! Any juicy gossip to share?</p>
              </div>
            </div>

            <div class="content">

              <%= form_for @gossip do |form| %>
                  <% if @gossip.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>

                      <ul>
                        <% gossip.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>

                  <div class="field">
                    <%= form.text_area :body, class: "textarea", value: "OMG! Turns out...", autofocus: true %>
                  </div>

                  <div class="actions">
                    <%= form.submit class: "button is-fullwidth is-link is-outlined" %>
                  </div>
              <% end %>

            </div>

          </div>
    <% else %>
          <div class="card-content">
            <h2 class="title is-3 is-spaced">Wana share some Gossip?<h2>
            <div class="columns is-1 is-variable">
                <div class="column">
                  <a href="#" class="button is-medium is-fullwidth is-link is-outlined">Sing-up</a>
                </div>
                <div class="column">
                  <a href="#" class="button is-medium is-fullwidth is-info is-outlined">Log-in</a>
                </div>
            </div>
          </div>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <div class="card user-profile-card is-hidden-touch">
      <div class="card-image">
        <figure class="image is-4by3">
          <img src="https://cdn.pixabay.com/photo/2020/03/28/15/20/cat-4977436_960_720.jpg" alt="Placeholder image">
        </figure>
      </div>
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-48x48">
              <%= gravatar_image_tag(current_user.email, alt: current_user.name) %>
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4"><%= current_user.name %></p>
            <p class="subtitle is-6">@<%= current_user.username %></p>
          </div>
        </div>

        <div class="content">
          <span><%= current_user.gossips.count%> Gossips<span>
          <span class="inline-separator"> . </span>
          <span>30 followrs</span>
          <span class="inline-separator"> . </span>
          <span>20 followings</span>
        </div>
      </div>
    </div>
  <% end %>
  <nav class="panel panel-trend">
    <p class="panel-heading side-panel">Top 3 most commented Gossips</p>
    <a href="" class="panel-block">Trend 1</a>
    <a href="" class="panel-block">Trend 1</a>
    <a href="" class="panel-block">Trend 1</a>
  </nav>
  <nav class="panel">
    <p class="panel-heading side-panel">Top 3 new Gossip</p>
    <a href="" class="panel-block">Trend 1</a>
    <a href="" class="panel-block">Trend 1</a>
    <a href="" class="panel-block">Trend 1</a>
  </nav>
</div>

app/views/gossips/_who-to-follow.html.erb
<div class="column">
  <nav class="panel">
    <p class="panel-heading side-panel">Who to follow</p>
  </nav>

  <% @users.each do |user| %>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <%= gravatar_image_tag(user.email, alt: user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= user.name %></strong>
              <small>@<%= user.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
  <% end %>

</div>

app/views/gossips/edit.html.erb
<div class="section">
  <div class="columns is-centred">
    <div class="column"></div>
    <div class="column is-6">

        <article class="panel is-info">
          <p class="panel-heading">
            Editting Gossip
          </p>
          <div class="px-4 py-2">
            <%= render 'form', gossip: @gossip %>
          </div>

        </article>
      
        <div class="devise-links">
          <%= link_to 'Cancel', gossips_path, class: "mr-4"%>
          <%= link_to 'Home', gossips_path %>
        </div>

    </div>
    <div class="column"></div>
  </div>
</div>

app/views/gossips/index.html.erb
<section class="section">
  <!-- <div class="container has-background-info"> -->
  <div class="columns">
    <%= render 'trends' %>
    <%= render 'feed' %>
    <%= render 'who-to-follow' %>
  </div>
  <!-- </div> -->
</section>

app/views/gossips/new.html.erb
<div class="section">
  <div class="columns is-centred">
    <div class="column"></div>
    <div class="column is-6">

        <article class="panel is-info">
          <p class="panel-heading">
            Create Gossip
          </p>
          <div class="px-4 py-2">
            <%= render 'form', gossip: @gossip %>
          </div>

        </article>
      
        <div class="devise-links">
          <%= link_to 'Cancel', gossips_path, class: "mr-4"%>
          <%= link_to 'Home', gossips_path %>
        </div>

    </div>
    <div class="column"></div>
  </div>
</div>

app/views/gossips/show.html.erb
<div class= "columns mt-5">
  <div class="column is-1"></div>
  <div class="column is-10">
    <div class="gossip-container">

          <div class="name-lockup">

            <%= gravatar_image_tag(@gossip.user.email, alt: @gossip.user.name, class: "avatar") %>
            <div class="name"><%= @gossip.user.name %> <span>@<%= @gossip.user.username%></span></div>

          </div>

          <blockquote>
            <%= @gossip.body %>
          </blockquote>

          <div class="actions">
            <i class="icon-reply fa fa-reply-all"></i>
            <i class="icon-spread fa fa-bullhorn"> 0</i>
            <i class="icon-like fa fa-heart"> 1</i>
            <i class="icon-dislike fa fa-thumbs-o-down"> 0</i>
            <i class="icon-comment fa fa-comment-o"> 0</i>
            <% if user_signed_in? %>
              <i class="icon-quote-gossiper fa fa-quote-right"> 0</i>
              <%= link_to @gossip, class: "icon-show" do %>
                <i class="fa fa-link"></i>
              <% end %>
              <%= link_to edit_gossip_path(@gossip), class: "icon-edit" do %>
                <i class="fa fa-pencil-square-o"></i>
              <% end %>
              <%= link_to @gossip, method: :delete, data: { confirm: 'Are you sure you want to delete this Gossip?' }, class: "icon-delete" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            <% end %>
          </div>

          <span class="time"><%= time_ago_in_words(@gossip.created_at) %> ago</span>

    </div>
  </div>
  <div class="column is-1"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>MyTwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="has-navbar-fixed-top">

    <%= render 'partials/nav'%>
    <%= render 'partials/flash'%>
    <%= yield %>

  </body>

  <%= render 'partials/footer'%>

</html>

app/views/partials/_flash.html.erb
    <% if flash[:notice] %>
      <div class="notification is-success global-notification is-radiusless is-light">
        <button class="delete"></button>
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification is-radiusless is-light">
        <button class="delete"></button>
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

app/views/partials/_footer.html.erb
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong class="brand-logo">GossipLand</strong> by <a href="#">Houda Cherkaoui</a>. The source code is licensed
        <a href="#">MIT</a>.
      </p>
    </div>
  </footer>

app/views/partials/_nav.html.erb
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">

        <%= link_to root_path, class: "navbar-item brand-logo" do %>
              <h1>GossipLand</h1>
        <% end %>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to "Home", root_path, class: "navbar-item"%>

          <%= link_to "Gossip", new_gossip_path, class: "navbar-item"%>

          <a class="navbar-item" href="#">
            Trends
          </a>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item">
                Contact
              </a>
              <hr class="navbar-divider">
              <a class="navbar-item">
                Report an issue
              </a>
            </div>
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <% if user_signed_in? %>
              <span class="ml-3 mr-5" ><%= link_to "@"+current_user.username, edit_user_registration_path, class: "has-text-warning"%></span>
              <%= link_to "Log Out >>", destroy_user_session_path, method: :delete, class: "button is-warning is-outlined" %>
            <% else %>
              <%= link_to "Log-in", new_user_session_path, class: "button is-light is-outlined mr-3" %>
              <%= link_to "Sign-up", new_user_registration_path, class: "button is-warning is-outlined" %>
            <%end%>
          </div>
        </div>
      </div>
    </nav>